stages:
  - setup
  - build
  - test

setup:
  stage: setup
  script:
    - pip install -r requirements.txt

build:
  stage: build
  script:
    - python hello.py

test:
  stage: test
  script:
    - python -m unittest discover
